### ISSUE TITLE
Why do we need the `ontowiki_` prefix for the permalinks?

### ISSUE THREAD

**Issue by white-gecko** [AKSW/docs.ontowiki.net#2]
Why do we need to prefix all pages in `ontowiki/` with `ontowiki_` for the permalinks? can't we just call them as they are?

**Comment by shinobu** [comment]
actually i couldn't call the links until i added `ontowiki_` in the url.yaml for every file in ontowiki/
i guess thats the way how the theme deals with the multi-folder-jekyll issue -> all files become unique through adding the foldername
i will look if i can somehow (without dropping all files into the root) solve this

**Comment by shinobu** [comment]
solved in e5ab781

i guess with the change from version 4 to 5 from the jekyll theme we did back then, they made it possible to remove the foldername_ from the permalinks
